all:
 hosts:
  target_hosts:
   ansible_host: "{{ host_placeholder }}" # it is update dynamically and no one  will be about it.
   ansible_user: "{{ user_placeholder }}"
   ansible_ssh_private_key_file: ~/.ssh/id_rsa
