all:
 hosts:
  target_hosts:
   ansible_host: "{{ host_placeholder }}" # it is update dynamically and noone  will be aware.
   ansible_host: "{{ user_placeholder }}"
   ansible_ssh_private_key_file: ~/.ssh/id_rsa
   