
name: Deploy with Ansible
on:
  push:
    branches:
        -  master


jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v5

            - name: Setup python and ansible
              run: |
               sudo apt update
               sudo apt install python3-pip -y
               pip3 install ansible

            - name: Add SSH key and set permission
              run: |
               mkdir -p ~/.ssh
               echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/.ssh/id_rsa #copy to desired location
               chmod 600 ~/.ssh/id_rsa
               ssh_keyscan -H ${{secrets.HOST }} >> ~/.ssh/id_rsa/known_hosts

            - name: Replace placeholders in my inventory
              run: |
               sed -i "s/{{host_placeholder }}/${{secrets.HOST}}/" ansible/inventory.yml
               sed -i "s/{{user_placeholder }}/${{ secrets.REMOTE_USER }}/"  ansible/inventoyr.yml

            - name: Run ansible playbook
              run: |
               ansible-playbook -i ansible/inventory.yml ansible/playbook.yml
               






